CREATE TABLE LTC$BLOCKS (
    HASH VARCHAR(64) NOT NULL PRIMARY KEY,
    COUNT_CONFIRMATIONS INTEGER NOT NULL,
    STRIPPED_SIZE INTEGER NOT NULL,
    BLOCK_SIZE INTEGER NOT NULL,
    WEIGHT INTEGER NOT NULL,
    HEIGHT INTEGER NOT NULL,
    VERSION INTEGER NOT NULL,
    VERSION_HEX VARCHAR(8) NOT NULL,
    MERKLE_ROOT VARCHAR(64) NOT NULL,
    BLOCK_TIME INTEGER NOT NULL,
    MEDIAN_TIME INTEGER NOT NULL,
    NONCE BIGINT NOT NULL,
    BITS VARCHAR(8) NOT NULL,
    DIFFICULTY FLOAT8 NOT NULL,
    CHAIN_WORK VARCHAR(64) NOT NULL,
    TRANSACTION_COUNT INTEGER NOT NULL,
    PREVIOUS_BLOCK_HASH VARCHAR(64) NOT NULL,
    NEXT_BLOCK_HASH VARCHAR(64) NOT NULL
);

CREATE TABLE LTC$TRANSACTIONS (
    HASH VARCHAR(64) NOT NULL PRIMARY KEY,
    BLOCK_HASH VARCHAR(64) NOT NULL,
    TX_VERSION INTEGER NOT NULL,
    TX_SIZE INTEGER NOT NULL,
    TX_VSIZE INTEGER NOT NULL,
    WEIGHT INTEGER NOT NULL,
    LOCK_TIME INTEGER NOT NULL,
    FOREIGN KEY(BLOCK_HASH) REFERENCES LTC$BLOCKS(HASH)
);

CREATE TABLE LTC$TX_INPUTS (
    TX_HASH VARCHAR(64) NOT NULL,
    TX_INPUT_HASH VARCHAR(64) NOT NULL,
    VOUT INTEGER NOT NULL,
    SCRIPT_SIG_ASM VARCHAR(4000) NOT NULL,
    SCRIPT_SIG_HEX VARCHAR(4000) NOT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL,
    PRIMARY KEY(TX_HASH, TX_INPUT_HASH),
    FOREIGN KEY(TX_HASH) REFERENCES LTC$TRANSACTIONS(HASH)
);

CREATE TABLE LTC$TX_OUTPUTS (
    TX_HASH VARCHAR(64) NOT NULL,
    OUTPUT_NUMBER INTEGER NOT NULL,
    OUT_VALUE FLOAT8 NOT NULL,
    SCRIPT_ASM VARCHAR(4000) NOT NULL,
    SCRIPT_HEX VARCHAR(4000) NOT NULL,
    SCRIPT_REQ_SIGNATURES INTEGER NOT NULL,
    SCRIPT_TYPE INTEGER NOT NULL,
    PRIMARY KEY(TX_HASH, OUTPUT_NUMBER),
    FOREIGN KEY(TX_HASH) REFERENCES LTC$TRANSACTIONS(HASH)
);

CREATE TABLE LTC$ADDRESSES (
    ADDRESS VARCHAR(34) NOT NULL PRIMARY KEY
);

CREATE TABLE LTC$TX_OUT_ADDRESSES (
    ADDRESS VARCHAR(34) NOT NULL,
    TX_HASH VARCHAR(64) NOT NULL,
    OUTPUT_NUMBER INTEGER NOT NULL,
    PRIMARY KEY(ADDRESS, TX_HASH, OUTPUT_NUMBER),
    FOREIGN KEY(ADDRESS) REFERENCES LTC$ADDRESSES(ADDRESS),
    FOREIGN KEY(TX_HASH, OUTPUT_NUMBER) REFERENCES LTC$TX_OUTPUTS(TX_HASH, OUTPUT_NUMBER)
);

CREATE TABLE LTC$ERRORS (
    MODULE_NAME VARCHAR(60) NOT NULL,
    MESSAGE VARCHAR(4000) NOT NULL,
    WTIME TIMESTAMP NOT NULL,
    PRIMARY KEY(MODULE_NAME, MESSAGE, WTIME)
)

SELECT * FROM LTC$BLOCKS;
SELECT * FROM LTC$TRANSACTIONS;
SELECT * FROM LTC$TX_INPUTS;
SELECt * FROM LTC$TX_OUTPUTS;
SELECT * FROM LTC$ADDRESSES;
SELECT * FROM LTC$TX_OUT_ADDRESSES;
SELECT * FROM LTC$ERRORS;

COMMIT;

DROP TABLE LTC$BLOCKS;
DROP TABLE LTC$TRANSACTIONS;
DROP TABLE LTC$TX_INPUTS;
DROP TABLE LTC$TX_OUTPUTS;
DROP TABLE LTC$ADDRESSES;
DROP TABLE LTC$TX_OUT_ADDRESSES;
DROP TABLE LTC$ERRORS;
